@startuml General Workflow

start
:Check references;
if (Module) then(Current Module)
    if(Object) then (Model)
        :Add Model to list;
    endif
endif
while (Each Model in List)
    :Render Model;
end while
:Return rendered UML;
stop
@enduml
